### ISSUE TITLE
Doesn't need to be a Flutter package

### ISSUE THREAD

**Issue by isoos** [RobluScouting/EvalEx#2]
I haven't checked in depth, but it seems that the package can be used on Dart too, except that the current `pubspec.yaml` specifies that it depends on Flutter. Would you consider to remove that dependency?

**Comment by aidan-mundy** [comment]
@widavies this should be fine

**Comment by widavies** [comment]
Good point, I just removed the dependency on the Flutter SDK and uploaded a release for it. Thanks for pointing this out.
