### ISSUE TITLE
A value of type 'Rational' can't be assigned to a variable of type 'Decimal'

### ISSUE THREAD

**Issue by evanwsu** [RobluScouting/EvalEx#3]
eval_ex-1.1.6/lib/built_ins.dart:86:25: Error: A value of type 'Rational' can't be assigned to a variable of type 'Decimal'.
 - 'Rational' is from 'package:rational/rational.dart'.
 - 'Decimal' is from 'package:decimal/decimal.dart'.
    Decimal intPow = v1.pow(n2IntPart.toBigInt().toInt());

**Comment by widavies** [comment]
@evansherry Thanks for letting me know!

Fixed in 35eac244c3c4d4cc743a988b2736684e99b9e57c

Available as 1.1.7: https://pub.dev/packages/eval_ex/versions
